### ISSUE TITLE
Playing music results in an error as there is no resolution associated with it

### ISSUE THREAD

**Issue by krohrsb** [mvantassel/plexpy2influx#10]
When playing music, `plexpy2influx` generates invalid data to be sent to influx.

```
message: 'A 400 Bad Request error occurred: {"error":"unable to parse \'sessions,resolution= direct_stream_count=1,direct_stream_playing_count=1,total_stream_count=1,total_stream_playing_count=1,transcode_stream_count=0,transcode_stream_playing_count=0\': missing tag value"}\n' }
```

Assume its associated with the fact that `resolution=` has no value.

**Comment by mvantassel** [comment]
hey @blackbarn, thanks for logging an issue.

I don't have music in my plex but I'll get around to adding a song so I can reproduce what's going on here.

**Comment by mvantassel** [comment]
Added a check that should resolve this issue.

`
let tags = {
  resolution: data.type ? data.type.toLowerCase() : null
};
`
