### ISSUE TITLE
repository name must be lowercase

### ISSUE THREAD

**Issue by kylechx** [mvantassel/plexpy2influx#12]
So I have a more 'complex' setup w/ influxdb on a linux box, plexpy on a windows data server, and docker on a server 2016 distro.

When I try to run the command using the triggers I am getting an error:

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: invalid reference format: repository name must be lowercase.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

Here is the command I am running:
```
docker run -d -e INFLUXDB_HOST="IP" INFLUXDB_DB="plexpy" INFLUXDB_USER="usr" INFLUXDB_PASS="psw" PLEXPY_TOKEN="TOKEN" PLEXPY_HOST="IP" matthewvantassel/plexpy2influx
```

**Comment by mvantassel** [comment]
Hey @kylechx,

Welcome to github!

I have not seen that error before so I did some searching on google and it seems to be related to docker version and windows specifically. The error reported is not helpful as the repository -is- lowercase.

I'd encourage you to google `invalid reference format: repository name must be lowercase.` and try some of the solutions provided in other projects.

Thanks! Hope you're able to resolve your issue.
