### ISSUE TITLE
Error Parsing Library data

### ISSUE THREAD

**Issue by TheDevouringOne** [mvantassel/plexpy2influx#14]
Trying to get Tautulli v2 to push to Grafana and the plexpy2influx docker is returning this in the logs over and over:

Thu Jan 11 2018 08:37:25 GMT+0000 (UTC): Parsing PlexPy User Data
Thu Jan 11 2018 08:37:25 GMT+0000 (UTC): Error -- Cannot read property 'forEach' of undefined
[TypeError: Cannot read property 'forEach' of undefined]
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Initialize PlexPy2Influx
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Getting PlexPy Activity Data
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Getting PlexPy Library Data
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Getting PlexPy User Data
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Parsing PlexPy Activity Data
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Error -- Cannot read property 'length' of undefined
[TypeError: Cannot read property 'length' of undefined]
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Parsing PlexPy Library Data
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Error -- libraryData.forEach is not a function
[TypeError: libraryData.forEach is not a function]
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Parsing PlexPy User Data
Thu Jan 11 2018 08:37:26 GMT+0000 (UTC): Error -- Cannot read property 'forEach' of undefined
[TypeError: Cannot read property 'forEach' of undefined]

On the Tautulli logs I am getting this:

  |   |  
-- | -- | --
2018-01-11 08:37:26 | DEBUG | Tautulli APIv2 :: Cleaned kwargs: None
2018-01-11 08:37:26 | DEBUG | Tautulli APIv2 :: Invalid apikey.
2018-01-11 08:37:26 | DEBUG | Tautulli APIv2 :: API called with kwargs: {'cmd': u'get_users_table', 'apikey': u'********7a'}

I have tried device keys for like the Android which return the above and the normal Plexpy / Tautulli API key doesn't connect at all. No data is being written in the InfluxDB database.

**Comment by mvantassel** [comment]
Hey @TheDevouringOne,

This repo only supports PlexPy V1. Tautulli V2 has breaking API changes so I will be creating a new repo specifically for v2 e.g. `tautulli2influx` when it's out of beta.

Thanks!
