### ISSUE TITLE
list what metrics it exports in readme, add examples, etc

### ISSUE THREAD

**Issue by evanrich** [mvantassel/plexpy2influx#8]
needs better documentation.   Could you provide a sample of metrics it outputs?   users have to go through your code to see what you're grabbing from plexpy, should list it on the readme.

**Comment by mvantassel** [comment]
Hey @evanrich, great idea. I'll create a section in the `README.md` with a list of metrics and example payloads.

**Comment by mvantassel** [comment]
@evanrich take a look at the attached PR and let me know if that is enough or if you're looking for Grafana dashboard examples too.

**Comment by mvantassel** [comment]
Closing the issue as README.md was updated
